### ISSUE TITLE
Can it be used together with ip adapter+controllnet? Can hyper-sd acceleration be used

### ISSUE THREAD

**Issue by libai-lab** [czg1225/AsyncDiff#2]
Can it be used together with ip adapter+controllnet? Can hyper-sd acceleration be used

**Comment by czg1225** [comment]
Hi @libai-lab ,
AsyncDiff can be integrated with both Adapter and ControlNet. We provide detailed examples on how to use AsyncDiff with ControlNet and SDXL at [here](https://github.com/czg1225/AsyncDiff/blob/main/src/examples/run_sdxl_controlnet.py). Additionally, we offer examples demonstrating the use of AsyncDiff with AnimateDiff, including the motion adapter. You can find these examples [here](https://github.com/czg1225/AsyncDiff/blob/main/src/examples/run_animatediff.py).

**Comment by czg1225** [comment]
Hi @libai-lab ,
After checking the paper of Hyper-SD, I think AsyncDiff may have difficulties in supporting Hyper-SD.
